from app.domain.exceptions.exceptions import ValueObjectError

__all__ = ["ValueObjectError"]
